GET http://localhost:5000/todos

###

POST http://localhost:5000/todo/new
content-Type: application/json

{
    "text": "Get the jam"
}

###

DELETE http://localhost:5000/todo/delete/635d11c6aeb51ab11706b3b4

###

PUT http://localhost:5000/todo/complete/635d1223aeb51ab11706b3b6


